---
- name: Get instance info 
  hosts: localhost
  tasks:
  
    - name: block to fetch in mem invetory
      block:  
        - name: Fetch Instance Info
          os_server_info:
            cloud: openstack
            region_name: regionOne
          register: r_os_servers

        - name: Add host
          add_host:
            name: "{{ item.public_v4 }}"
            ansible_user: cloud-user
            group:
              - "{{ item.metadata.group }}"
              - "{{ item.metadata.deployment_name }}"
          loop: "{{ r_os_servers.openstack_servers }}"
      tags:
        - application_servers
        - database_servers
        - load_balancers
