---
- name: Deploy, configure, and populate Postgres 10
  hosts: database_servers
  remote_user: cloud-user
  become: true
  gather_facts: false
  tags:
    - database_servers
  roles:
    - postgres
